import { join } from 'node:path';
import { existsSync, appendFileSync, writeFileSync } from 'node:fs';
import * as readline from 'node:readline/promises';
import { openDb } from '../core/db.js';
import { MemoryStore } from '../core/store.js';
import { resolveProjectId } from '../core/project_id.js';
import { projectDir } from '../config.js';
import type { Observation, ObservationKind } from '../core/schema.js';

// Suggest CLAUDE.md additions based on accumulated observations.
// Interactive and off by default — user must explicitly run this command.

const KIND_HEADER: Record<ObservationKind, string> = {
  decision: '## Decisions',
  learning: '## Learnings',
  bugfix: '## Known Issues / Fixes',
  command: '## Useful Commands',
  file_summary: '## Key Files',
  other: '## Notes',
};

function formatSuggestion(obs: Observation): string {
  return `- **${obs.title}** — ${obs.body.split('\n')[0] ?? obs.body}`;
}

function groupByKind(obs: Observation[]): Map<ObservationKind, Observation[]> {
  const m = new Map<ObservationKind, Observation[]>();
  for (const o of obs) {
    const list = m.get(o.kind) ?? [];
    list.push(o);
    m.set(o.kind, list);
  }
  return m;
}

function buildClaudeMdSection(grouped: Map<ObservationKind, Observation[]>): string {
  const sections: string[] = [
    '<!-- Generated by `somtum suggest-claude-md`. Review and edit before committing. -->',
  ];
  for (const [kind, items] of grouped) {
    if (items.length === 0) continue;
    sections.push(`\n${KIND_HEADER[kind]}\n`);
    for (const obs of items.slice(0, 8)) {
      sections.push(formatSuggestion(obs));
    }
  }
  return sections.join('\n');
}

export async function suggestClaudeMdCommand(opts: {
  cwd?: string;
  limit?: number;
  yes?: boolean;
  dry?: boolean;
  dbPath?: string;
  projectId?: string;
}): Promise<number> {
  const cwd = opts.cwd ?? process.cwd();
  const projectId = opts.projectId ?? resolveProjectId(cwd);
  const dbPath = opts.dbPath ?? join(projectDir(projectId), 'db.sqlite');

  if (!existsSync(dbPath)) {
    console.error('somtum: no database found — run `somtum init` first');
    return 1;
  }

  const db = openDb({ path: dbPath });
  const store = new MemoryStore(db);

  try {
    // Pick the most token-saving observations, excluding file_summary (too granular for CLAUDE.md).
    const all = store
      .listByProject(projectId)
      .filter((o) => o.kind !== 'file_summary')
      .sort((a, b) => b.tokens_saved - a.tokens_saved)
      .slice(0, opts.limit ?? 30);

    if (all.length === 0) {
      console.log('No observations to suggest. Run a few Claude sessions first.');
      return 0;
    }

    const grouped = groupByKind(all);
    const section = buildClaudeMdSection(grouped);

    const claudeMdPath = join(cwd, 'CLAUDE.md');
    const exists = existsSync(claudeMdPath);

    console.log('\nProposed additions to CLAUDE.md:\n');
    console.log('─'.repeat(60));
    console.log(section);
    console.log('─'.repeat(60));
    console.log(`\nTarget: ${claudeMdPath}${exists ? ' (will append)' : ' (will create)'}`);

    if (opts.dry) {
      console.log('\n[dry-run] No changes written.');
      return 0;
    }

    if (!opts.yes) {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      try {
        const answer = await rl.question('\nAppend to CLAUDE.md? [y/N] ');
        if (answer.trim().toLowerCase() !== 'y') {
          console.log('Aborted.');
          return 0;
        }
      } finally {
        rl.close();
      }
    }

    const toWrite = `\n\n${section}\n`;
    if (exists) {
      appendFileSync(claudeMdPath, toWrite, 'utf8');
    } else {
      writeFileSync(claudeMdPath, `# Project Memory\n${toWrite}`, 'utf8');
    }
    console.log(`\nWrote ${section.split('\n').length} lines to ${claudeMdPath}.`);
    console.log('Review the additions and remove anything outdated or incorrect.');
    return 0;
  } finally {
    db.close();
  }
}
