import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDb, type DB } from '../core/db.js';
import { MemoryStore } from '../core/store.js';
import { Bm25Retriever } from '../core/retriever/bm25.js';
import { runPostSession } from './post_session.js';
import { ConfigSchema } from '../core/schema.js';
import type { LlmCaller } from '../core/extractor.js';

let tmp: string;
let db: DB;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'somtum-hook-'));
  db = openDb({ path: join(tmp, 'db.sqlite') });
});

afterEach(() => {
  db.close();
  rmSync(tmp, { recursive: true, force: true });
});

const FIXTURE_TRANSCRIPT = `
User: Let's use pnpm for this project.
Assistant: Good call — pnpm's workspaces + strict hoisting work well for monorepos.
User: Also the Bearer abc.def.ghi token in the staging env should never be logged.
Assistant: Noted. I'll add a redaction pattern for that.
User: The auth bug was caused by a stale JWT iss claim. Fixed in src/auth/session.ts.
Assistant: Root cause confirmed and fix committed.
`;

const CANNED_EXTRACTION = {
  observations: [
    {
      kind: 'decision',
      title: 'Use pnpm for this project',
      body: 'Picked pnpm for its workspaces and strict hoisting.',
      files: ['package.json'],
      tags: ['tooling'],
    },
    {
      kind: 'bugfix',
      title: 'Auth bug caused by stale JWT iss',
      body: 'Bearer abc.def.ghi appeared in logs; fixed in src/auth/session.ts. Cause: stale iss claim.',
      files: ['src/auth/session.ts'],
      tags: ['auth'],
    },
  ],
};

function fakeCaller(): LlmCaller {
  return {
    async complete() {
      return {
        text: JSON.stringify(CANNED_EXTRACTION),
        inputTokens: 100,
        outputTokens: 50,
      };
    },
  };
}

describe('runPostSession — integration: transcript → extractor → store → search', () => {
  it('captures observations, redacts secrets, and a BM25 search finds them', async () => {
    const config = ConfigSchema.parse({});
    const indexPath = join(tmp, 'index.md');

    const result = await runPostSession(
      {
        transcript: FIXTURE_TRANSCRIPT,
        session_id: 'sess-1',
        project_id: 'proj-test',
        cwd: tmp,
      },
      {
        cwd: tmp,
        config,
        caller: fakeCaller(),
        db,
        indexPath,
        projectName: 'fixture',
      },
    );

    expect(result.inserted).toBe(2);

    const store = new MemoryStore(db);
    const all = store.listByProject('proj-test');
    expect(all).toHaveLength(2);

    // Redaction ran at the boundary — the bearer token must not be in the DB.
    const bodies = all.map((o) => o.body.toLowerCase()).join(' ');
    expect(bodies).not.toContain('abc.def.ghi');

    // BM25 retriever finds the bugfix observation by keyword.
    const retriever = new Bm25Retriever(db);
    const hits = await retriever.search('auth jwt', { k: 5, projectId: 'proj-test' });
    expect(hits.length).toBeGreaterThan(0);
    expect(hits[0]?.observation.kind).toBe('bugfix');

    // index.md was generated with the header comment.
    const md = readFileSync(indexPath, 'utf8');
    expect(md).toContain('regenerated by somtum');
    expect(md).toContain('# fixture Memory Index');
    expect(md).toContain('2 memories');
  });

  it('inserts 0 observations when extractor returns empty (still writes index)', async () => {
    const emptyCaller: LlmCaller = {
      async complete() {
        return { text: JSON.stringify({ observations: [] }), inputTokens: 5, outputTokens: 5 };
      },
    };
    const config = ConfigSchema.parse({});
    const indexPath = join(tmp, 'index.md');

    const r = await runPostSession(
      { transcript: 'nothing useful', session_id: 's', project_id: 'proj', cwd: tmp },
      { cwd: tmp, config, caller: emptyCaller, db, indexPath, projectName: 'fixture' },
    );
    expect(r.inserted).toBe(0);
    expect(readFileSync(indexPath, 'utf8')).toContain('0 memories');
  });

  it('rejects a payload missing both transcript and transcript_path', async () => {
    const config = ConfigSchema.parse({});
    await expect(
      runPostSession(
        { session_id: 's', cwd: tmp } as unknown as Parameters<typeof runPostSession>[0],
        { cwd: tmp, config, caller: fakeCaller(), db },
      ),
    ).rejects.toThrow();
  });
});
