import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname } from 'node:path';
import type { MemoryStore } from './store.js';
import type { Observation, ObservationKind } from './schema.js';

const HEADER_COMMENT =
  '<!-- This file is regenerated by somtum. Edits will be overwritten. To modify, use: somtum edit <id> -->';

const KIND_TITLES: Record<ObservationKind, string> = {
  decision: 'Decisions',
  learning: 'Learnings',
  bugfix: 'Bugfixes',
  file_summary: 'File summaries',
  command: 'Commands',
  other: 'Other',
};

const ISO_DAY = (ms: number) => new Date(ms).toISOString().slice(0, 10);

function groupByKind(obs: Observation[]): Record<ObservationKind, Observation[]> {
  const out: Record<ObservationKind, Observation[]> = {
    decision: [],
    learning: [],
    bugfix: [],
    file_summary: [],
    command: [],
    other: [],
  };
  for (const o of obs) out[o.kind].push(o);
  return out;
}

function fileReferenceCounts(obs: Observation[]): Map<string, string[]> {
  const map = new Map<string, string[]>();
  for (const o of obs) {
    for (const f of o.files) {
      const list = map.get(f) ?? [];
      list.push(o.id);
      map.set(f, list);
    }
  }
  return map;
}

function formatLine(o: Observation): string {
  const files = o.files.length > 0 ? ` — ${o.files.map((f) => `\`${f}\``).join(', ')}` : '';
  return `- [${ISO_DAY(o.created_at)}] \`${o.id}\` ${o.title}${files}`;
}

export interface IndexOptions {
  projectName: string;
  totalTokensSaved: number;
  now?: number;
  recentDays?: number;
}

export function renderIndex(obs: Observation[], opts: IndexOptions): string {
  const now = opts.now ?? Date.now();
  const recentDays = opts.recentDays ?? 7;
  const recentCutoff = now - recentDays * 24 * 60 * 60 * 1000;

  const byKind = groupByKind(obs);
  const byFile = fileReferenceCounts(obs);
  const recent = obs
    .filter((o) => o.created_at >= recentCutoff)
    .sort((a, b) => b.created_at - a.created_at);

  const sections: string[] = [];

  sections.push(HEADER_COMMENT);
  sections.push('');
  sections.push(`# ${opts.projectName} Memory Index`);
  sections.push('');
  sections.push(
    `Last updated: ${new Date(now).toISOString()}. ${obs.length} memories. ${opts.totalTokensSaved} tokens saved cumulative (estimated).`,
  );
  sections.push('');

  sections.push('## By kind');
  sections.push('');
  for (const kind of Object.keys(KIND_TITLES) as ObservationKind[]) {
    const list = byKind[kind];
    if (list.length === 0) continue;
    sections.push(`### ${KIND_TITLES[kind]} (${list.length})`);
    sections.push('');
    const sorted = [...list].sort((a, b) => b.created_at - a.created_at);
    for (const o of sorted) sections.push(formatLine(o));
    sections.push('');
  }

  if (byFile.size > 0) {
    sections.push('## By file (most-referenced)');
    sections.push('');
    const entries = [...byFile.entries()].sort((a, b) => b[1].length - a[1].length).slice(0, 20);
    for (const [file, ids] of entries) {
      sections.push(`- \`${file}\` — ${ids.length} memories: ${ids.map((i) => `\`${i}\``).join(', ')}`);
    }
    sections.push('');
  }

  sections.push(`## Recent (last ${recentDays} days)`);
  sections.push('');
  if (recent.length === 0) {
    sections.push('- _none_');
  } else {
    for (const o of recent) sections.push(formatLine(o));
  }
  sections.push('');

  return sections.join('\n');
}

export interface GenerateOptions extends IndexOptions {
  store: MemoryStore;
  projectId: string;
  outputPath: string;
}

export function generateIndex(options: GenerateOptions): string {
  const obs = options.store.listByProject(options.projectId);
  const md = renderIndex(obs, options);
  const dir = dirname(options.outputPath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(options.outputPath, md, 'utf8');
  return md;
}
