import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openDb, type DB } from './db.js';
import { MemoryStore } from './store.js';
import { renderIndex, generateIndex } from './index_gen.js';

let tmp: string;
let db: DB;
let store: MemoryStore;

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'somtum-idx-'));
  db = openDb({ path: join(tmp, 'db.sqlite') });
  store = new MemoryStore(db);
});

afterEach(() => {
  db.close();
  rmSync(tmp, { recursive: true, force: true });
});

describe('renderIndex', () => {
  it('produces the regen-warning header and title', () => {
    const md = renderIndex([], { projectName: 'acme', totalTokensSaved: 0, now: Date.UTC(2026, 3, 19) });
    expect(md).toContain('regenerated by somtum');
    expect(md).toContain('# acme Memory Index');
    expect(md).toContain('0 memories');
  });

  it('omits empty kind sections and groups by referenced files', () => {
    const now = Date.now();
    const a = store.insert({
      project_id: 'p1',
      session_id: 's',
      kind: 'decision',
      title: 'Use pnpm',
      body: 'workspaces',
      files: ['package.json'],
      created_at: now - 1000,
    });
    const b = store.insert({
      project_id: 'p1',
      session_id: 's',
      kind: 'bugfix',
      title: 'Fix auth',
      body: 'cause',
      files: ['package.json', 'src/auth.ts'],
      created_at: now,
    });

    const obs = store.listByProject('p1');
    const md = renderIndex(obs, { projectName: 'acme', totalTokensSaved: 123, now });

    expect(md).toContain('### Decisions (1)');
    expect(md).toContain('### Bugfixes (1)');
    expect(md).not.toContain('### Learnings');
    expect(md).toContain('## By file');
    expect(md).toContain('`package.json` — 2 memories');
    expect(md).toContain(a.id);
    expect(md).toContain(b.id);
  });

  it('includes observations newer than the recent cutoff', () => {
    const now = Date.now();
    store.insert({
      project_id: 'p1',
      session_id: 's',
      kind: 'decision',
      title: 'Old',
      body: '.',
      created_at: now - 30 * 24 * 60 * 60 * 1000,
    });
    store.insert({
      project_id: 'p1',
      session_id: 's',
      kind: 'decision',
      title: 'New',
      body: '.',
      created_at: now - 1000,
    });

    const md = renderIndex(store.listByProject('p1'), {
      projectName: 'acme',
      totalTokensSaved: 0,
      now,
      recentDays: 7,
    });
    expect(md).toMatch(/## Recent \(last 7 days\)[\s\S]+New/);
    // Old still appears in By kind; check it's not in Recent section
    const recentSection = md.split('## Recent')[1] ?? '';
    expect(recentSection).not.toContain('Old');
  });
});

describe('generateIndex', () => {
  it('writes the rendered markdown to disk', () => {
    store.insert({
      project_id: 'p1',
      session_id: 's',
      kind: 'learning',
      title: 'Something',
      body: 'x',
    });
    const out = join(tmp, 'index.md');
    const written = generateIndex({
      projectName: 'acme',
      totalTokensSaved: 0,
      store,
      projectId: 'p1',
      outputPath: out,
    });
    expect(readFileSync(out, 'utf8')).toBe(written);
  });
});
